baseURL = "https://zuckberj.netlify.app/"
languageCode = "en-us"
title = "Victor's Page"

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "@zuckberj"
description = "My personal page."
name = "Victor Santos"
[params.picture]
src = "/images/me2.jpg"
alt = ""
