baseURL = "https://zuckberj.netlify.app/"
languageCode = "en-us"
title = "Victor's Page"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    description = "My personal page."
    author = "@zuckberj"
